### ISSUE TITLE
Incorrect block name in IS module deployment.toml

### ISSUE THREAD

**Issue by nilushancosta** [wso2/puppet-is#120]
**Description:**
The block "[keystore.tls]" in the IS module's deployment.toml file must be corrected as "[keystore.primary]".
This is because there is no such variable named "keystore.tls" in any of the j2 files in the product pack. However there is a variable named "keystore.primary" in the carbon.xml.j2 file for which a corresponding "[keystore.primary]" block is missing in the deployment.toml file

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilushancosta** [comment]
I tried to submit a PR to fix this issue by following the contribution guideline given in this repository. However the 5.8.x branch is using the configuration files that were used before the introduction of the deployment.toml file. It does not contain a deployment.toml file. Could you please let me know how to submit the fix?

**Comment by Savidude** [comment]
Hi Nilushan. We created a branch for ongoing development on Puppet modules for IS 5.9.0 at [1]. Please submit your fixes to that. Thanks.

[1] https://github.com/wso2/puppet-is/tree/5.9.x
